articles:
    resource: "@ArticlesBundle/Controller/"
    type:     annotation
    prefix:   articles/

users:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation
    prefix:   users/

sessions:
    resource: "@UserBundle/Controller/SessionController.php"
    type:     annotation
    prefix:   session/

app:
    resource: '@AppBundle/Controller/'
    type: annotation
