articles:
    resource: "@ArticlesBundle/Controller/ArticleController.php"
    type:     annotation
    prefix:   articles/

tags:
    resource: "@ArticlesBundle/Controller/TagController.php"
    type:     annotation
    prefix:   admin/tags/

category:
    resource: "@ArticlesBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   admin/category/

users:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation
    prefix:   users/

sessions:
    resource: "@UserBundle/Controller/SessionController.php"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
