security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database_users:
          entity: { class: UserBundle:User}

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                remember_me: true
            logout:
                path:   /logout
                target: /login
                success_handler:      ~
                invalidate_session:   true
                delete_cookies:
                    # Prototype
                    name:
                        path:                 ~
                        domain:               ~
                handlers:             []
            anonymous: ~

            remember_me:
                secret: "%secret%"
                name: ab-store
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~
                secure: false
                httponly: true
                always_remember_me: false
                remember_me_parameter: 'login[remember_me]'

#            remember_me:
#                key: 'who_belled_the_cat'
#                lifetime: 31536000 # 365 days in seconds
#                path:     /
#                domain:   ~ # Defaults to the current domain from $_SERVER
#                remember_me_parameter: 'login[remember_me]'
            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        - {path: ^/admin, roles: ROLE_SUPER_ADMIN}
        - {path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}