security:
    encoders:
        UserBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: UserBundle:User, property: email }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /



    access_control:
        - {path: ^/admin, roles: ROLE_ADMIN}
        - {path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}