<?php

namespace ArticlesBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 * @return array
	 */
	public function findAllByCategory($categoryName){
		return $this->getEntityManager()
			->createQueryBuilder()
			->select(array('a.id','a.title','a.link','a.description','a.imageUrl'))
			->from('ArticlesBundle:Article', 'a')
			->innerJoin('ArticlesBundle:Category','c')
			->where('a.category = c')
			->andWhere('c.name = :categoryName')
			->setParameter('categoryName', $categoryName)
			->getQuery()
			->getResult()
			;
	}


}
